---
# This playbook adds a key for the ansible_user into the home folder
- hosts: all
  become: yes
  tasks:
    - name: Add id_ed25519 public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"


