---
# This playbook disables the IPv6 stack on the server (runtime)
- name: Disable IPv6 system-wide
  hosts: homelab
  become: true
  tasks:
    - name: Ensure sysctl settings for IPv6 are disabled
      copy:
        dest: /etc/sysctl.d/99-disable-ipv6.conf
        content: |
          net.ipv6.conf.all.disable_ipv6 = 1
          net.ipv6.conf.default.disable_ipv6 = 1
          net.ipv6.conf.lo.disable_ipv6 = 1
        owner: root
        group: root
        mode: '0644'

    - name: Apply sysctl settings immediately
      command: sysctl --system

